name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: zip -r website.zip .
      - uses: softprops/action-gh-release@v1
        with:
          files: website.zip
