name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # Необходимо для создания релизов

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Для получения истории тегов

      - name: Create ZIP archive
        run: |
          # Исключаем ненужные файлы
          zip -r website.zip . \
            -x '*.git*' '*node_modules*' '*.env*'

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            website.zip
          generate_release_notes: true
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
